sudo: required

services:
  - docker

env:
  - BASE_VERSION=1.4
  - BASE_VERSION=1.5
  - BASE_VERSION=1.6
  - BASE_VERSION=1.7
  - BASE_VERSION=1.8
  - BASE_VERSION=1.9
  - BASE_VERSION=1.10
  - BASE_VERSION=1.11
  - BASE_VERSION=1.12

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t cd2team/docker-golang:$BASE_VERSION ./ --build-arg BASE_VERSION=$BASE_VERSION

deploy:
  provider: script
  script: "docker push cd2team/docker-golang:$BASE_VERSION"
